spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/teste_db?allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:fiap}
    password: ${MYSQL_PASSWORD:fiap}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

server:
  port: ${PORT:8080}